# Generated by Django 6.0.7 on 2026-07-23 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('current_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending Manager'), ('PENDING_APP_OWNER', 'Pending Application Owner'), ('PENDING_SECURITY', 'Pending Security'), ('INFO_REQUESTED', 'Info Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('returned_from_state', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='Portal.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REQUESTER', 'Requester'), ('MANAGER', 'Line Manager'), ('APP_OWNER', 'Application Owner'), ('SECURITY', 'Security Team')], max_length=30)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending Manager'), ('PENDING_APP_OWNER', 'Pending Application Owner'), ('PENDING_SECURITY', 'Pending Security'), ('INFO_REQUESTED', 'Info Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30)),
                ('to_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending Manager'), ('PENDING_APP_OWNER', 'Pending Application Owner'), ('PENDING_SECURITY', 'Pending Security'), ('INFO_REQUESTED', 'Info Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RETURN', 'Return for Info'), ('RESUBMIT', 'Resubmit')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Portal.accessrequest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
