# Generated by Django 6.0.7 on 2026-07-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='returned_from_state',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending Manager'), ('PENDING_APP_OWNER', 'Pending Application Owner'), ('PENDING_SECURITY', 'Pending Security'), ('INFO_REQUESTED', 'Info Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30, null=True),
        ),
    ]
