# Generated by Django 6.0.7 on 2026-08-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_alter_accessrequest_returned_from_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='logo',
            field=models.CharField(blank=True, help_text='Relative path under frontend/public/, e.g. images/app-logos/slack.png', max_length=255),
        ),
    ]
